'use strict';
const $ = id => document.getElementById(id);
let key=sessionStorage.getItem('voca-admin-key')||'',selected=null,service=null,sites=[],timer=null,testBusy=false;
const testResults=new Map(),testDrafts=new Map();
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function message(text){$('message').textContent=text;}
async function api(path,body,method){const response=await fetch('/api/admin/'+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+key,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(60000)});const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed.');return result;}
function action(label,run,cls=''){const b=el('button',label,cls);b.type='button';b.onclick=async()=>{message('');b.disabled=true;try{await run();}catch(e){message(e.message);}finally{b.disabled=false;}};return b;}
async function load(){service=await api('status');sites=(await api('sites')).sites;$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;$('service-status').textContent=service.ai_configured?'Answer provider preference: '+service.answer_provider+' · '+(service.answer_provider==='Gemini'?service.gemini_model:service.model)+(service.openai_configured&&service.gemini_configured?' · Gemini fallback configured':''):'Content imports can run. Add your AI API key to the service to enable answers, then choose Prepare AI search.';$('ai-form').elements.model.value=service.model;$('ai-form').elements.gemini_model.value=service.gemini_model;if(!selected&&sites.length===1)selected=sites[0].id;renderSetup();renderChecks();renderSites();if(selected){const current=sites.find(s=>s.id===selected);if(current)await renderDetail(current);}}
function renderSites(){const container=$('sites');container.replaceChildren();if(!sites.length){container.append(el('div','No websites connected yet. Add your first website to start importing its content.','empty'));return;}sites.forEach(s=>{const b=el('button',undefined,'site');b.append(el('span',s.platform,'platform'),el('h2',s.name),el('p',s.origin));const metrics=el('div',undefined,'metrics');metrics.append(el('span',s.documents+' documents'),el('span',s.enabled?s.status:'Disabled'));b.append(metrics);b.onclick=async()=>{selected=s.id;await renderDetail(s);$('detail').scrollIntoView({behavior:'smooth',block:'nearest'});};container.append(b);});}
function readonly(value,label){const field=el('label',label);const input=el('input');input.value=value;input.readOnly=true;field.append(input);return field;}
async function renderDetail(s,newSecret){const panel=$('detail');panel.hidden=false;panel.replaceChildren();panel.append(el('h2',s.name),el('p',s.origin));if(s.error)panel.append(el('p',s.error,'danger'));if(newSecret){const box=el('div','Save this connection key. It is shown once and belongs only in your WordPress settings.','secret');box.append(el('code',newSecret));panel.append(box);}const instructions=el('div',undefined,'instructions');instructions.append(readonly(s.id,'Website ID'),readonly(service.base_url,'Agent service address'));
if(s.platform==='wordpress'){const list=el('ol');['Upload voca-agent-wordpress.zip in WordPress → Plugins → Add New → Upload Plugin, then activate it.','Open Settings → Voca Agent. Enter the service address, website ID and connection key.','Save settings. Published content imports automatically; updates are synced in the background.'].forEach(x=>list.append(el('li',x)));instructions.append(list);}
if(s.platform==='shopify'){instructions.append(el('p','Connect the app below to import products, collections, pages and policies. Then open your theme’s App embeds, enable Voca, and enter the service address and website ID above.'));const input=el('input');input.id='shop-domain';input.placeholder='your-store.myshopify.com';input.value=s.shop||'';input.ariaLabel='Shopify store hostname';instructions.append(input);}
if(s.platform==='webflow'){instructions.append(el('p','Connect Webflow to scan the published website and install the guide. Your Webflow site ID is '+s.remote_id+'. Publish the site in Webflow when ready so the widget becomes visible.'));}
panel.append(instructions);const actions=el('div',undefined,'actions');if(s.platform!=='wordpress')actions.append(action('Connect '+(s.platform==='shopify'?'Shopify':'Webflow'),async()=>{const result=await api('sites/'+s.id+'/connect',{shop:$('shop-domain')?.value.trim()||''});window.location.assign(result.url);},'primary'));
if(s.platform!=='wordpress')actions.append(action('Refresh content',async()=>{await api('sites/'+s.id+'/scan',{});message('Content refresh queued.');await load();}));actions.append(action('Prepare AI search',async()=>{await api('sites/'+s.id+'/embed',{});message('AI indexing queued.');}));if(s.platform==='webflow')actions.append(action('Install guide',async()=>{await api('sites/'+s.id+'/install_widget',{});message('Installation queued. Publish your Webflow site after it finishes.');}));if(s.platform==='wordpress')actions.append(action('New connection key',async()=>{if(!confirm('Replace the current connection key? Update WordPress settings with the new key.'))return;const r=await api('sites/'+s.id+'/rotate_key',{});await renderDetail(s,r.connection_key);}));actions.append(action(s.enabled?'Disable guide':'Enable guide',async()=>{await api('sites/'+s.id+'/enabled',{enabled:!s.enabled});await load();}));actions.append(action('Delete website',async()=>{if(!confirm('Delete this website and its imported knowledge?'))return;const r=await api('sites/'+s.id,undefined,'DELETE');selected=null;panel.hidden=true;await load();if(r.publish_required)message('Publish the Webflow site to complete widget removal.');},'danger'));panel.append(actions);
const stats=el('p',s.embedded_chunks+' of '+s.chunks+' content sections prepared for AI. Last content sync: '+(s.last_sync?new Date(s.last_sync*1000).toLocaleString():'Not yet'));panel.append(stats);panel.append(el('p','Search index: '+((s.search_models||[]).join(', ')||'Not prepared'),'muted'));renderTester(panel,s);await renderExtras(panel,s);
const [docs,jobs]=await Promise.all([api('sites/'+s.id+'/documents'),api('sites/'+s.id+'/jobs')]);
const health=el('section',undefined,'content-health');health.append(el('h3','Content health'));
const oldPages=docs.documents.filter(d=>!d.fresh).length;
health.append(el('p',oldPages?oldPages+' of '+docs.documents.length+' indexed pages need a refresh. Freshness is based on the last successful index time.':'All indexed pages were refreshed recently. Freshness is based on the last successful index time.','muted'));
const retry=action(s.platform==='wordpress'?'Open WordPress sync settings':'Retry full content sync',async()=>{if(s.platform==='wordpress'){window.open(s.origin+'/wp-admin/options-general.php?page=voca-agent','_blank','noopener');return;}await api('sites/'+s.id+'/scan',{});message('Content refresh queued.');await load();},'');health.append(retry);
if(docs.truncated)health.append(el('p','Showing the first 1,000 indexed pages.','muted'));
health.append(el('h3','Recent sync activity'));jobs.jobs.slice(0,5).forEach((j,index)=>{const row=el('div',undefined,'sync-activity');row.append(el('strong',j.kind.replaceAll('_',' ')+' · '+j.status),el('span',new Date(j.finished||j.created).toLocaleString(),'muted'));if(j.error)row.append(el('p',j.error,'danger'));if(j.result&&j.result!=='{}'){const report=el('details');report.append(el('summary','View sync report'),el('pre',JSON.stringify(JSON.parse(j.result),null,2)));row.append(report);}if(index===0&&(j.status==='failed'||s.status==='error'||s.status==='partial'))row.append(action(s.platform==='wordpress'?'Open WordPress sync settings':'Retry sync',async()=>{if(s.platform==='wordpress'){window.open(s.origin+'/wp-admin/options-general.php?page=voca-agent','_blank','noopener');return;}await api('sites/'+s.id+'/scan',{});message('Content refresh queued.');await load();}));health.append(row);});panel.append(health);
panel.append(el('h3','Imported content'));const wrap=el('div',undefined,'table-wrap'),table=el('table');const header=el('tr');['Page / product','Type','Last indexed','Status','Action'].forEach(x=>header.append(el('th',x)));table.append(header);docs.documents.forEach(d=>{const row=el('tr'),title=el('td'),a=el('a',d.title||d.url);a.href=d.url;a.target='_blank';a.rel='noopener noreferrer';title.append(a);const preview=action('Preview indexed text',async()=>{const data=await api('sites/'+s.id+'/preview?document='+encodeURIComponent(d.id));const existing=title.querySelector('pre');if(existing)existing.remove();const text=el('pre',data.text+(data.truncated?'\n[Preview shortened]':''));title.append(text);});preview.className='preview-button';title.append(preview);const indexed=el('td',new Date(d.updated*1000).toLocaleString());const status=el('td',d.fresh?'Recent':'Needs refresh',d.fresh?'freshness-good':'freshness-stale');const controls=el('td');controls.append(action('Exclude',async()=>{await api('sites/'+s.id+'/exclude',{document:d.id});message('Page removed from the guide and excluded from future syncs.');await load();}));row.append(title,el('td',d.kind),indexed,status,controls);table.append(row);});wrap.append(table);panel.append(wrap);
if(docs.excluded.length){panel.append(el('h3','Excluded pages'));panel.append(el('p','These pages are removed from answers and skipped during future syncs. Restore a page to include it again.','muted'));const excludedWrap=el('div',undefined,'table-wrap'),excludedTable=el('table'),excludedHead=el('tr');['Page','Excluded','Action'].forEach(x=>excludedHead.append(el('th',x)));excludedTable.append(excludedHead);docs.excluded.forEach(d=>{const row=el('tr'),title=el('td'),a=el('a',d.title||d.url);a.href=d.url;a.target='_blank';a.rel='noopener noreferrer';title.append(a);row.append(title,el('td',new Date(d.excluded*1000).toLocaleString()),el('td'));row.lastChild.append(action('Restore',async()=>{const result=await api('sites/'+s.id+'/include',{document:d.id});if(result.refresh_required){message('Page restored. Run Refresh content in WordPress to import it again.');return;}message('Page restored and a content refresh was queued.');await load();}));excludedTable.append(row);});excludedWrap.append(excludedTable);panel.append(excludedWrap);}}

$('login-form').onsubmit=async e=>{e.preventDefault();key=$('admin-key').value.trim();try{await load();sessionStorage.setItem('voca-admin-key',key);$('admin-key').value='';message('');startPolling();}catch(err){message(err.message);}};
$('logout').onclick=()=>{sessionStorage.removeItem('voca-admin-key');key='';clearInterval(timer);$('login').hidden=false;$('workspace').hidden=true;$('logout').hidden=true;};
$('add-button').onclick=()=>$('create-dialog').showModal();$('close-dialog').onclick=()=>$('create-dialog').close();
$('create-form').elements.platform.onchange=()=>{$('remote-field').hidden=$('create-form').elements.platform.value!=='webflow';$('create-form').elements.remote_id.required=!$('remote-field').hidden;};
$('create-form').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));if(b.platform!=='webflow')delete b.remote_id;try{const s=await api('sites',b);$('create-dialog').close();e.target.reset();$('remote-field').hidden=true;e.target.elements.remote_id.required=false;selected=s.id;await load();await renderDetail(s,s.platform==='wordpress'?s.connection_key:undefined);message('Website added. Follow the connection steps below.');}catch(err){message(err.message);}};
function startPolling(){clearInterval(timer);timer=setInterval(async()=>{if(document.hidden||$('create-dialog').open||testBusy||$('detail').contains(document.activeElement))return;try{const fresh=(await api('sites')).sites;const changed=JSON.stringify(fresh)!==JSON.stringify(sites);if(changed){sites=fresh;renderSetup();renderSites();if(selected){const s=sites.find(x=>x.id===selected);if(s)await renderDetail(s);}}}catch{}},6000);}
if(key)load().then(startPolling).catch(e=>{sessionStorage.removeItem('voca-admin-key');message(e.message);});
$('ai-form').onsubmit=async event=>{event.preventDefault();const form=event.target;const button=form.querySelector('button[type=submit]');button.disabled=true;try{await api('ai',Object.fromEntries(new FormData(form)));form.elements.key.value='';form.elements.gemini_key.value='';await load();message('AI connection saved. Imported content is being prepared for answers.');}catch(error){message(error.message);}finally{button.disabled=false;}};

function chooseSiteForSetup(){
  const current=sites.find(s=>s.id===selected)||sites[0];
  if(!current){$('create-dialog').showModal();return;}
  selected=current.id;renderDetail(current).then(()=>$('detail').scrollIntoView({behavior:'smooth'}));
}
function renderSetup(){
  const box=$('setup-guide');box.replaceChildren(el('h2','Get your guide ready'));
  const connected=sites.length>0,ready=sites.some(s=>s.chunks>0&&s.embedded_chunks===s.chunks&&!s.error);
  const steps=[
    ['1','Connect a website',connected?'Website added':'Choose WordPress, Shopify or Webflow',connected,()=>$('create-dialog').showModal()],
    ['2','Connect your AI',service.ai_configured?'Keys saved · use Check connection to verify':'Save at least one provider key',service.ai_configured,()=>{document.querySelector('.ai-settings').open=true;document.querySelector('.ai-settings').scrollIntoView({behavior:'smooth'});}],
    ['3','Import website content',ready?'Content ready for search':'Open a website for import instructions',ready,chooseSiteForSetup],
    ['4','Test your answers',testResults.size?'An answer test completed in this session':'Try a question and inspect its sources',testResults.size>0,chooseSiteForSetup]
  ];
  const grid=el('div',undefined,'setup-grid');
  steps.forEach(([n,title,detail,done,run])=>{const b=action('',run,'setup-step');b.append(el('span',done?'✓':n,'step-number'),el('strong',title),el('span',detail));grid.append(b);});box.append(grid);
}
function renderChecks(){
  const box=$('connection-checks');box.replaceChildren(el('p','Checks use a short fictional example to verify search and answers. Provider usage may be billed.','muted'));
  ['openai','gemini'].forEach(provider=>{const row=el('div',undefined,'check-row'),result=el('span','Not checked this session','muted');const b=action('Check '+(provider==='openai'?'OpenAI':'Gemini'),async()=>{result.textContent='Checking search and answers…';try{const r=await api('ai/check',{provider});result.textContent='Working · '+r.model+' · '+r.seconds+'s';}catch(e){result.textContent=e.message;}});b.disabled=!service[provider+'_configured'];row.append(b,result);box.append(row);});
}
function renderTester(panel,s){
  const box=el('section',undefined,'answer-tester');box.id='answer-tester';box.append(el('h3','Test your guide'),el('p','Ask a website question, then inspect the answer and the excerpts used. Tests are not saved as conversations.','muted'));
  const form=el('form');const questionLabel=el('label','Your test question'),question=el('textarea');question.rows=3;question.maxLength=2000;question.required=true;question.placeholder='What services does this website offer?';question.value=testDrafts.get(s.id)||'';question.oninput=()=>testDrafts.set(s.id,question.value);questionLabel.append(question);
  const languageLabel=el('label','Answer language'),language=el('select');[['auto','Match my question'],['en-US','English'],['ur-PK','Urdu'],['ar-SA','Arabic'],['hi-IN','Hindi'],['es-ES','Spanish'],['fr-FR','French'],['de-DE','German'],['pt-BR','Portuguese'],['zh-CN','Chinese'],['ja-JP','Japanese']].forEach(([value,label])=>{const o=el('option',label);o.value=value;language.append(o);});languageLabel.append(language);
  const consent=el('label',undefined,'test-consent'),check=el('input');check.type='checkbox';check.required=true;consent.append(check,el('span','Send this question and relevant website excerpts to the configured AI provider.'));
  const button=el('button','Test answer','primary');button.type='submit';button.disabled=!service.ai_configured||!s.embedded_chunks;
  const output=el('div');output.setAttribute('role','status');
  function show(r){output.replaceChildren();const answer=el('p',r.answer,'test-answer');answer.dir='auto';output.append(answer,el('p',r.provider+' · '+r.model+' · '+r.seconds+' seconds · Search: '+r.search_model,'muted'));output.append(el('h4','Cited sources'));if(!r.sources.length)output.append(el('p','No sources cited. Verify that the response correctly acknowledges missing information.'));r.sources.forEach(source=>{const a=el('a',source.title);a.href=source.url;a.target='_blank';a.rel='noopener noreferrer';output.append(a,el('br'));});const details=el('details');details.append(el('summary','View retrieved excerpts ('+r.excerpts.length+')'));r.excerpts.forEach(x=>{details.append(el('h4',x.source_id+' · '+x.title),el('pre',x.text));});output.append(details);}
  if(testResults.has(s.id))show(testResults.get(s.id));
  form.onsubmit=async event=>{event.preventDefault();if(testBusy)return;testBusy=true;button.disabled=true;output.textContent='Searching the website and preparing an answer…';try{const r=await api('sites/'+s.id+'/test',{message:question.value.trim(),language:language.value});testResults.set(s.id,r);show(r);renderSetup();}catch(e){output.textContent=e.message;}finally{testBusy=false;button.disabled=false;}};
  form.append(questionLabel,languageLabel,consent,button);box.append(form,output);panel.append(box);
}

async function renderExtras(panel,s){
 const [settings,usage]=await Promise.all([api('sites/'+s.id+'/appearance'),api('sites/'+s.id+'/usage')]);
 const section=el('section',undefined,'answer-tester');section.append(el('h3','Brand & contact handoff'),el('p','Customize the visitor guide. Contact handoff opens your contact page or email app; it does not start a live support chat.','muted'));
 const form=el('form');
 [['name','Guide name',80],['launcher','Launcher label',40],['welcome','Welcome message',400],['color','Brand color',7],['handoff_label','Contact button label',60],['handoff_url','Contact URL or mailto email',1000]].forEach(([name,label,max])=>{const field=el('label',label),input=el('input');input.name=name;input.value=settings[name];input.maxLength=max;if(name==='color')input.type='color';if(name==='handoff_url')input.placeholder='https://yourwebsite.com/contact';field.append(input);form.append(field);});
 const label=el('label','Widget position'),select=el('select');select.name='position';['right','left'].forEach(value=>{const option=el('option',value==='right'?'Bottom right':'Bottom left');option.value=value;select.append(option);});select.value=settings.position;label.append(select);form.append(label);
 const save=el('button','Save appearance','primary');save.type='submit';const status=el('p','');status.setAttribute('role','status');form.append(save,status);
 form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{await api('sites/'+s.id+'/appearance',Object.fromEntries(new FormData(form)));status.textContent='Saved. Refresh the website to see the changes.';}catch(e){status.textContent=e.message;}finally{save.disabled=false;}};section.append(form);panel.append(section);
 const stats=el('section',undefined,'answer-tester');stats.append(el('h3','Usage · last 30 days'),el('p','Daily totals in UTC. No visitor messages, IP addresses, or contact details are stored. Collection begins with this update; handoff counts are link clicks, not completed contacts.','muted'));
 const content=el('div');function show(u){content.replaceChildren();const grid=el('div',undefined,'setup-grid');[['Questions',u.totals.requests],['Answers',u.totals.answers],['Errors',u.totals.errors],['Contact clicks',u.totals.handoffs],['Without citations',u.totals.uncited],['Average answer time',u.totals.average_seconds+'s'],['OpenAI answers',u.totals.openai],['Gemini answers',u.totals.gemini]].forEach(([label,value])=>{const card=el('div',undefined,'setup-step');card.append(el('strong',String(value)),el('span',label));grid.append(card);});content.append(grid);if(!u.daily.length)content.append(el('p','No visitor activity recorded yet. Dashboard tests are excluded.','muted'));else{const table=el('table'),head=el('tr');['Date','Questions','Answers','Errors','Contact clicks'].forEach(x=>head.append(el('th',x)));table.append(head);u.daily.forEach(d=>{const row=el('tr');[d.day,d.requests,d.answers,d.errors,d.handoffs].forEach(x=>row.append(el('td',String(x))));table.append(row);});const wrap=el('div',undefined,'table-wrap');wrap.append(table);content.append(wrap);}}
 show(usage);stats.append(content,action('Refresh usage',async()=>show(await api('sites/'+s.id+'/usage'))));panel.append(stats);
}
